{% set version = "1.9.0" %}

package:
  name: doctr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/doctr/doctr-{{ version }}.tar.gz
  sha256: 952aba39c776d5660ea7737b43b44ddabed21798df16d7517910de3641d030f7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - doctr = doctr.__main__:main

requirements:
  host:
    - python >=3.5
    - pip
    - requests
    - cryptography
    - pyyaml

  run:
    - python >=3.5
    - requests
    - cryptography
    - pyyaml

test:
  imports:
    - doctr

  commands:
    - doctr --help
    - doctr configure --help
    - doctr deploy --help

about:
  home: https://drdoctr.github.io/doctr/index.html
  license: MIT
  summary: Deploy docs from Travis to GitHub pages.

  description: |
    A tool for automatically building docs on Travis CI, and deploying
    them to GitHub pages.
  doc_url: https://drdoctr.github.io/doctr/index.html
  dev_url: https://github.com/drdoctr/doctr

extra:
  recipe-maintainers:
    - asmeurer
    - gforsyth
    - scopatz
