{% set version = "1.7.4" %}

package:
  name: doctr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/doctr/doctr-{{ version }}.tar.gz
  sha256: 02baf3c53da2211d12e5dba60a44d937b3758e706127d83f7b4a54c508bfc286

build:
  number: 1000
  skip: true  # [py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - doctr = doctr.__main__:main

requirements:
  build:
    - python
    - pip
    - requests
    - cryptography
    - pyyaml

  run:
    - python
    - requests
    - cryptography
    - pyyaml

test:
  imports:
    - doctr

  commands:
    - doctr --help
    - doctr configure --help
    - doctr deploy --help

about:
  home: https://drdoctr.github.io/doctr/index.html
  license: MIT
  summary: 'Deploy docs from Travis to GitHub pages.'

  description: |
    A tool for automatically building docs on Travis CI, and deploying
    them to GitHub pages.
  doc_url: https://drdoctr.github.io/doctr/index.html
  dev_url: https://github.com/drdoctr/doctr

extra:
  recipe-maintainers:
    - asmeurer
    - gforsyth
    - scopatz
