appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YTm6bJSJIIrCo2QKnydvjDshtdPrAUhjv66r1k9P9R1MpOR7KxTFvnD55SUTQXs+pMBBmUpseQdLaIPM1tZBS6UvWVJg+rSaZOHczv3QujKhd+90jff3Kw5hfrU/QGh+3mrUvr8PKupqbIH4qgO/JDEl5M+W+jJDuG8ev6JDZIEubvqeltFBLeTOBMO92zaEkYMYlSWRRSqBrnty6Itg2ypxNDvhw3xfQYHf52bkhUNqqkAdeTxmI+Z5RjeC5M2gtIo14MrmmY/68hW3F1hcTpDx/bIzvJYscP2flSsbZEx0kvsWKT5WHJUWTMCbhLSTbV+Ra9H67LfQKaYbsTl1smDfnKV5jat83dLBqa5Gp1Sio1+fTDOshgozz4Ht//5uvKGjR0Ca+GwLC8SkTRThu8LDn3DFqwj8zbkIwG5oN5ip3e9JBcWal6L3AgKdQWK1uN7eDZ6TJZ9iSA4zSbP/va1EJacSRMLq+KVwQ4fOSr/VTX/cHo4XmeYTsdxhWrnW3VfYITET1H10H/OzsurgjjYKQFImFuGhc+flk0hD7vg/jaeajS/w8DNvCNZdlBCmJhabv2A4CbkxdiiW+hkhk9Nu4BdhDOxFeAJ7nmy8KHBgwuKOXyz9uWTPSziVqZxGrI3m0JJ18XNaO8tysEd/Qm6S4TNVPwD9OmdiRwmMWcY=}
provider:
  win: azure
